version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: db
    environment:
      - INFLUXDB_DB=network_telemetry
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=supersecretpassword
    volumes:
      - $PWD/influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - $PWD:/var/lib/influxdb/

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/database:/var/lib/grafana/

  ping:
    image: federico87/network_telemetry_ping:latest
    container_name: ping
    restart: always

  tcp:
    image: federico87/network_telemetry_tcp:latest
    container_name: tcp
    restart: always
